version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  selenium-node-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenium-network

networks:
  selenium-network:
