services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  selenium-node-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    networks:
      - selenium-network

networks:
  selenium-network:


