services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  selenium-node-chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    depends_on:
      - selenium-hub

